services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./Backend/uploads:/app/uploads
  frontend:
    build:
      context: ./frontend/my-app
    container_name: frontend
    ports:
      - "3000:3000"